version: "3.4"

services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node:0-16-bullseye
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    privileged: true
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - v2ray
    # Uncomment the next line to use a non-root user for all processes.
    # user: node

  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    networks:
      - v2ray
    volumes:
      - ./v2ray:/etc/v2ray

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - v2ray
    ports:
      - 80:80
    links:
      - v2ray
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always

networks:
  v2ray: